export const Questions = [
  {
    prompt: "What is my Klab?",
    optionA: "John",
    optionB: "Jake",
    optionC: "Josh",
    optionD: "William",
    optionE: "Pro",
    answer: "D",
  },
  {
    prompt: "Which of this is not a programming language?",
    optionA: "Python",
    optionB: "JavaScript",
    optionC: "MC-03",
    optionD: "Java",
    optionE: "PHP",
    answer: "C",
  },
  {
    prompt: "Which of this is not a javascript framework?",
    optionA: "React",
    optionB: "Angular",
    optionC: "Vue",
    optionD: "Java",
    optionE: "Next",
    answer: "D",
  },
  {
    prompt: "Mention the most difficult programming language among the following?",
    optionA: "C programming",
    optionB: "Java programming",
    optionC: "Python",
    optionD: "JavaScript",
    optionE: "C++",
    answer: "A",
  },
  {
    prompt: "Which of the following programing is easier?",
    optionA: "Python",
    optionB: "Ruby",
    optionC: "Go",
    optionD: "C++",
    optionE: "JavaScript",
    answer: "A",
  },
];